### ISSUE TITLE
No way to gracefully cancel a task when it fails.

### ISSUE THREAD

**Issue by matthew798** [gridsum/DataflowEx#15]
Sorry, I know this isnt really an issue it's just that there isn't even a tag for this library on SO.

Is there a way to cancel a task (a work unit) if it fails (throws an exception)?

I have a few flows that do a lot of file IO over a network and exceptions can happen, so far I have seen no mechanism that would allow me to just log the failure and continue with the other tasks as they come in. 

For example, I might have a flow that copies a file, then one that renames it, then one that zips it.

If copying the file fails, I want the copy flow to log the failure, and wait for more work.

Can this be done with DataFlowEx?

Thanks.

**Comment by karldodd** [comment]
Hi @matthew798 , from the perspective of DataflowEx, if a Dataflow instance fails, it will never recover to a healthy state again. So only let the instance down if something severe happens.

In your case, probably you should have some **try catch** code in your dataflow. Catch and log the IOException that may occasionally occur (maybe having some retries will be even better). The whole point is to avoid leaving these *expected* exceptions unhandled. This might help.
