### ISSUE TITLE
.Net Core 2.0 and logging?

### ISSUE THREAD

**Issue by BillHertzing** [gridsum/DataflowEx#17]
I have cloned the master repository currently at release v2.0.0, changed just the program.cs file under  Gridsum.DataflowEx.Demo so that slowflow demo is enabled (SlowFlowAsync on line 59) and the database demos are not enabled (commented lines 57, 65, and 71). When I build and run the demo, I expect to find the FlowMonitor and PerformanceMonitor log files. They don't seem to be getting created.
Is this a known issue, or a problem with my configuration? I'm running Visual Studio 2017 V15.2.5, Common.Logging V3.4.1, and App.Config in Gridsum.DataflowEx.Demo is specifying the NLog.NLogLoggerFactoryAdapter as Common.Logging.NLog20. 
NLog has come out with some much newer versions, including a V4.5-rc1 just a few days ago. 
Does the Demo src need some tweaks to get the logging working again?

**Comment by karldodd** [comment]
Hi @BillHertzing , sorry for the late reply. For the SlowFlowAsync demo, I guess you bumped into the same problem as #19 . In SlowFlowAsync() you can try setting PerformanceMonitorMode to something other than Verbose to see if log files get created correctly.

The fix will come soon.
