### ISSUE TITLE
DataBroadcaster sends data only to the first linked target if it is used as output property

### ISSUE THREAD

**Issue by Vasar007** [gridsum/DataflowEx#26]
Hi. Recently, I was trying to move one of my pipeline from low-level `TPL Dataflow` to `DataflowEx` and I met quite an unexpected behavior (as I think).

Let's say, we have class `A` which is inherited from `Dataflow<TIn, TOut>` and `OutputBlock` property is equal to the output block of `DataBroadcaster` field:

```csharp
internal sealed class A : Dataflow<string, IReadOnlyList<string>>
{
    private readonly DataBroadcaster<string> _inputBroadcaster;

    private readonly DataBroadcaster<IReadOnlyList<string>> _resultBroadcaster;

    public override ITargetBlock<string> InputBlock =>
        _inputBroadcaster.InputBlock;

    public override ISourceBlock<IReadOnlyList<string>> OutputBlock =>
        _resultBroadcaster.OutputBlock;

    public A()
        : base(DataflowOptions.Default)
    {
        // Init code goes here.
    }
}
```

However, if I link this dataflow with several external targets, it sends data only to the first linked target:

```csharp
var a = new A();
var b1 = new TransformBlock<IReadOnlyList<string>, IReadOnlyList<string>>(d => d);
var b2 = new TransformBlock<IReadOnlyList<string>, IReadOnlyList<string>>(d => d);

a.LinkTo(b1); // b1 gets data from a.
a.LinkTo(b2); // b2 do not get data from a.
```

Is this behavior by design or not?

By the way, using `LinkToMultiple` solves the problem (but it would cost additional `DataBroadcaster` implicitly):

```csharp
a.LinkToMultiple(b1, b2); // b1 and b2 get data from a.
```

Changing `DataBroadcaster` to `BroadcastBlock` with `.ToDataflow()` call also fixes the problem.

If this example is poor, I can attach the full code to reproduce the issue.

**Comment by karldodd** [comment]
Hi @Vasar007, thanks for using DataflowEx.

The magic of DataBroadcaster works in the level of Dataflow rather than the level of Block. But the LinkTo() method of class A actually delegates the underlying linking down to the block level so it does not 'broadcast'. This is expected behavior by design, at least at this moment.

The workaround could be using 'LinkToMultiple()' as you mentioned (you don't need _resultBroadcaster in class A). Or another way is to expose _resultBroadcaster as a public property and call on it:

```C#
a.ResultBroadcaster.LinkTo(b1); // b1 gets data from a.
a.ResultBroadcaster.LinkTo(b2); // b2 do not get data from a.
```

Please have a try and see if it works.

**Comment by Vasar007** [comment]
@karldodd, thanks for reply! I simplified the logic of the current pipeliene a little bit with some usefull and handfull methods from `DataflowEx` and switched to `LinkToMultiple` instead of `DataBroadcaster` in my `Dataflow` class.

Current pipeline version works as I expected))
