### ISSUE TITLE
Using JoinBlock or equivalent

### ISSUE THREAD

**Issue by santoorman** [gridsum/DataflowEx#4]
Hello, trying to use Broadcast and Join Blocks to fork/join, doesn't seem really possible with DataflowEx...? Can't LinkTo joinBlock.Target1 or Target2  ... ?

**Comment by karldodd** [comment]
Hi, there is a DataBroadcaster in DataflowEx: (please notice its difference with BroadcastBlock)
https://github.com/gridsum/dataflowex#62-databroadcaster

There is no equivalent/wrapper of JoinBlock in DataflowEx at this moment. But you can still use DataflowEx as the handle of your graph and use low-level block linking inside your Dataflow class. (You need to handle completion propagation yourself)

**Comment by santoorman** [comment]
hi karl - thanks for info - any more guidance how to do the joining?  I am happy to share what I have with you....

**Comment by karldodd** [comment]
I'm not sure whether you get my point. As I mentioned, you can "use low-level block linking", which means you just "do the joining" in the normal TPL Dataflow way. (and if you want to use DataflowEx, register those linked blocks as children of a Dataflow graph.)
