### ISSUE TITLE
Elegant Way to Stop Processing a Dataflow

### ISSUE THREAD

**Issue by santoorman** [gridsum/DataflowEx#5]
hello, based on a condition in one of our subflows or "blocks", we would like to stop processing the current dataflow.  however, we do want to re-use the dataflow for many posts so I don't think want to propogate completion for all children after.  Can you think of an elegant way to do this?

thanks

**Comment by santoorman** [comment]
from what i found, way to do this would be to use a buffer block, something like this.  Do you agree or have an easier way?  

    var forwarder = new BufferBlock<SomeType>();
    forwarder.LinkTo(target1, item => matchesTarget1(item));
    forwarder.LinkTo(DataflowBlock.NullTarget<SomeType>(), item => !matchesTarget1(item));

**Comment by karldodd** [comment]
Hi @santoorman, though this is not a DataflowEx question (but a Dataflow one), my two cents here:

Suppose you have A -> B and want to reuse B. You can basically **unlink** A->B and then link C->B. Unlink is supported by calling `Dispose()` on the return value of LinkTo() method:

https://msdn.microsoft.com/en-us/library/hh194692(v=vs.110).aspx

Not sure if this is what you want.

**Comment by karldodd** [comment]
Close as there is no response. Please reopen if the problem still exists.
