### ISSUE TITLE
Where can I ask questions? 

### ISSUE THREAD

**Issue by erlis** [gridsum/DataflowEx#9]
Hi Dodd!

Thanks for the great work with DataflowEx, I started using it and so far it's great for the problem I'm solving. I have a couple of questions but I don't kwnow where to ask. 

Can you please give me some directions on where can I ask my questions? 

Thanks once more
Erlis

**Comment by karldodd** [comment]
Hey @erlis , sorry for the late reply. I am picking up this project and as promised, it will evolve.

If u have got any questions, please just ask here as an issue.
